### ISSUE TITLE
pdf.combined.js shall not be used in production

### ISSUE THREAD

**Issue by yurydelendik** [erikras/react-pdfjs#1]
pdf.combined.js is not optimal solution (it's equivalent of the `PDFJS.disableWorker = true;`), which means, for some PDF, the UI will be visibly slower and has a sub-par performance. Sometimes it will lock the UI and will bring the "slow script" dialog. It's recommended to use a web worker configuration when possible.

**Comment by erikras** [comment]
Thanks for that. :+1: 

What should be done, then? Some combination of `pdf.js` and `pdf.worker.js`?

**Comment by yurydelendik** [comment]
(Not an expert in react) but the pdf.js shall be used, however you shall point PDFJS.workerSrc to the pdf.worker.js. The latter must reside on the same web server as a web page (due to the web worker cross-origin limitations, that's a reason why CDN solution might not work)

**Comment by erikras** [comment]
Okay, but will the `require('pdfjs-dist/build/pdf.combined');` work?

I noticed some CORS talk on a "why isn't PDF.js on a CDN yet?" thread, but skimmed over it. Oops.

**Comment by yurydelendik** [comment]
> but will the require('pdfjs-dist/build/pdf.combined'); work?

Nope.

There is no easy way to address CDN issue atm. I recommend to bring pdfjs-dist as dependency (and lock into specific version), use pdf.js in the main page and configure workerSrc to point to pdf.worker.js. Using pdf.combined is easy thing to do, but not suitable for performant solutions.

**Comment by erikras** [comment]
Just to clarify, `pdf.worker.js` needs to be **_served from the http server_** at runtime?

**Comment by yurydelendik** [comment]
> Just to clarify, pdf.worker.js needs to be served from the http server at runtime?

A Web Worker run in separate thread (different from the main page context), so serving as separate resource is required for its instantiation. See https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by erikras** [comment]
Thank you, @yurydelendik, you've been very helpful. At the moment, I'm looking for developer speed over runtime performance, so I think I'll stick with `pdf.combined.js`, but when the balance tips in the other direction, I'll have this discussion to follow.
